<?php
/**
 * OhYesChat
 * @website Link: https://informatikon.com
 * @package Informatikon.Elgg
 * @subpackage Chat
 * @author $arsalanshah.informatikon
 * @copyright All right reserved Informatikon Technologies 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
 
class ptregister {



/**
* Get entity by id
*
* @access system
* @return return;
*/
public function getEntity($guid){
if(isset($guid)){
	 return get_entity($guid);
}
 return false;
}


/**
* Data Add
*
* @access system
* @return return;
kathe fora pu ekteleitai kapoio erwthma sql kaleitai h sunarthsh Data
*/
public static function Data($query, $type){
    global $CONFIG;	
	$query = str_replace('prefixes_', $CONFIG->dbprefix, $query);
	if(!empty($query) && $type == 'get'){
	  return get_data($query);	
	}
	if(!empty($query) && $type == 'delete'){
	  return delete_data($query);	
	}
	if(!empty($query) && $type == 'add'){
	  return insert_data($query);	
	}
	if(!empty($query) && $type == 'run'){
	  return run_sql_script($query);	
	}
}  
/* einai sunarthsh p xrhsimopoieitai g na kanei insert sto elgg_pt_register  */
public static function setdata($num_links, $pt_user, $pt_pass, $username){
		global $CONFIG;	
		
		if(ptregister::Data("INSERT INTO {$CONFIG->dbprefix}pt_register 
								   (`university`, `pt_username`, `password`, `username`) VALUES
								   ('$num_links', '$pt_user', '$pt_pass', '$username')", 'add')){
					     return true;	
					}
		
}

/**
* Setup pt_register
*
* @access system
* @return return;
kanei ektelesh to sql gia na dhmiourghsei to elgg_pt_register
*/
public function Setup(){
	global $CONFIG;	
	$plugin = elgg_get_plugins_path().'pt_register/setup/';
	try {
	ptregister::Data("{$plugin}ptregister.sql", 'run');
	} catch (Exception $e) {
			$msg = $e->getMessage();
			if (strpos($msg, 'already exists')) {
				$msg = elgg_echo('install:error:tables_exist');
			}
			register_error($msg);
			return false;
    }	
}


}//class
